using Pkg

Pkg.add("GLMakie")
Pkg.add("GraphMakie")
Pkg.add("Graphs")
Pkg.add("InteractiveDynamics")
Pkg.add("DataStructures")
Pkg.add("Random")
Pkg.add("Makie")
Pkg.add("Agents")
Pkg.add("POMDPs")
Pkg.add("MCTS")
Pkg.add("Random")
Pkg.add("Colors")
Pkg.add("D3Trees")
Pkg.add("StaticArrays")
Pkg.add("POMDPs")
Pkg.add("POMDPTools")
Pkg.add("MCTS")
Pkg.add("POMDPModels")
Pkg.add("Observables")
Pkg.add("CSV")
Pkg.add("DataFrames")
Pkg.add("Dates")
Pkg.add("AStarSearch")
